name: CI

on: 
  push:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn
  test:
    - run: yarn test
  # TODO: Fix, this is not ideal, it will clear cache each time
  clear:
      - run: node . clear:all